"""
RL Training Script (with Composite Vulnerability Weighting)

Supports: size cap, penalty, reward threshold, and multi-column vulnerability weighting.
Each country's vulnerability score is calculated as the mean of the specified columns.

Example:
  python rl_train_realdata_with_vulnerability.py \
    --epochs 1500 \
    --size-cap 6 \
    --size-penalty 1.0 \
    --reward-threshold 600 \
    --vulnerability-csv simulated_vulnerability_scores.csv \
    --vulnerability-columns VulnerabilityScore
"""

import argparse
import torch
from torch import nn, optim
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

# -------------------------------
# CLI Arguments
# -------------------------------
parser = argparse.ArgumentParser()
parser.add_argument("--epochs", type=int, default=1000)
parser.add_argument("--size-cap", type=int, default=8)
parser.add_argument("--size-penalty", type=float, default=1.0)
parser.add_argument("--reward-threshold", type=float, default=500.0)
parser.add_argument("--vulnerability-csv", type=str, default=None,
                    help="CSV with Country and one or more vulnerability columns.")
parser.add_argument("--vulnerability-columns", type=str, default="VulnerabilityScore",
                    help="Comma-separated column names to average (default: VulnerabilityScore)")
args = parser.parse_args()

EPOCHS = args.epochs
SIZE_CAP = args.size_cap
SIZE_PENALTY_ALPHA = args.size_penalty
REWARD_THRESHOLD = args.reward_threshold
VUL_CSV = args.vulnerability_csv
VUL_COLUMNS = args.vulnerability_columns.split(",")

# -------------------------------
# Load Core Data
# -------------------------------
cos_sim = np.load("outputs/cosine_similarity.npy")
influence_matrix = np.load("outputs/influence_matrix.npy")

cluster_df = pd.read_csv("outputs/table_countries_by_cluster.csv")
cluster_map = cluster_df.set_index("Country")["ClusterLabel"].to_dict()

# Load minor country index (generated by process_ratification_data.py;
# row order matches cosine_similarity.npy and influence_matrix.npy)
minor_df = pd.read_csv("outputs/minor_country_index.csv")
countries = minor_df["Country"].tolist()
index_to_country = {i: c for i, c in enumerate(countries)}
N = len(countries)

# -------------------------------
# Load Vulnerability Scores (Composite)
# -------------------------------
vulnerability_map = {}

if VUL_CSV:
    vul_df = pd.read_csv(VUL_CSV)
    if "Country" in vul_df.columns and all(col in vul_df.columns for col in VUL_COLUMNS):
        vul_df["CompositeScore"] = vul_df[VUL_COLUMNS].mean(axis=1).fillna(0.0)
        vulnerability_map = dict(
            zip(vul_df["Country"], vul_df["CompositeScore"]))
        print(f"Loaded composite vulnerability scores using columns: {', '.join(VUL_COLUMNS)}")
    else:
        print("WARNING: One or more vulnerability columns not found in CSV.")

# -------------------------------
# Reward Function
# -------------------------------


def tipping_score_reward(coalition_indices):
    """
    Calculate the reward for a coalition based on tipping score and optional
    vulnerability weighting.

    Args:
        coalition_indices (list[int]): Indices of countries in the coalition.

    Returns:
        float: The final reward value after applying penalty and thresholding.
    """
    if len(coalition_indices) < 2:
        return 0.0

    alignment = np.mean([
        cos_sim[i, j]
        for i in coalition_indices for j in coalition_indices if i < j
    ]) if len(coalition_indices) > 1 else 0.0

    spread = sum(
        influence_matrix[i, j]
        for i in coalition_indices for j in range(N)
        if j not in coalition_indices
    )

    clusters = {cluster_map.get(
        index_to_country[i], "Unknown") for i in coalition_indices}
    diversity = len(clusters)
    score = alignment * spread * diversity

    if vulnerability_map:
        v_scores = [vulnerability_map.get(
            index_to_country[i], 0.0) for i in coalition_indices]
        mean_vul = np.mean(v_scores)
        score *= (1 + 0.5 * mean_vul)

    if SIZE_PENALTY_ALPHA > 0:
        score /= len(coalition_indices) ** SIZE_PENALTY_ALPHA

    if REWARD_THRESHOLD is not None and score < REWARD_THRESHOLD:
        return 0.0

    return score

# -------------------------------
# Policy Network
# -------------------------------


class PolicyNetwork(nn.Module):
    """A simple sigmoid-based policy network for coalition inclusion probabilities."""

    def __init__(self, n):
        super().__init__()
        self.fc = nn.Linear(n, n)

    def forward(self, x):
        """
        Forward pass through the policy network.
        Args:
            x (Tensor): Input state vector.
        Returns:
            Tensor: Inclusion probabilities for each player.
        """
        return torch.sigmoid(self.fc(x))

# -------------------------------
# Training Loop
# -------------------------------


def train_rl_policy(n_nations=N, epochs=EPOCHS, lr=0.01):
    """
    Train the RL policy network using REINFORCE algorithm.

    Args:
        n_nations (int): Number of countries.
        epochs (int): Number of training steps.
        lr (float): Learning rate.

    Returns:
        tuple: Trained model, reward history, coalition sizes, and probability matrix.
    """
    train_model = PolicyNetwork(n_nations)
    optimizer = optim.Adam(train_model.parameters(), lr=lr)

    train_rewards, train_sizes, train_prob_history = [], [], []

    for _ in range(epochs):
        state = torch.rand(n_nations)
        probs = train_model(state)
        train_prob_history.append(probs.detach().numpy())

        mask = torch.bernoulli(probs).bool()
        coalition = torch.where(mask)[0].tolist()

        if len(coalition) < 2 or (SIZE_CAP and len(coalition) > SIZE_CAP):
            continue

        reward = tipping_score_reward(coalition)
        if reward == 0.0:
            continue

        log_probs = torch.log(probs[mask])
        loss = -log_probs.sum() * reward

        optimizer.zero_grad()
        loss.backward()
        optimizer.step()

        train_rewards.append(reward)
        train_sizes.append(len(coalition))

    return train_model, train_rewards, train_sizes, np.array(train_prob_history)

# -------------------------------
# Sampling Function
# -------------------------------


def sample_learned_coalitions(sample_model, threshold=0.5, n_samples=1000):
    """
    Sample coalitions from the trained policy using a fixed probability threshold.

    Args:
        model (nn.Module): Trained policy network.
        threshold (float): Probability cutoff for inclusion.
        n_samples (int): Number of samples to draw.

    Returns:
        list[tuple]: List of sampled coalition tuples.
    """
    sample_coalitions = []
    with torch.no_grad():
        for _ in range(n_samples):
            state = torch.rand(N)
            probs = sample_model(state)
            selected = (probs > threshold).nonzero().flatten().tolist()
            if 2 <= len(selected) <= (SIZE_CAP or N):
                named = tuple(sorted(index_to_country[i] for i in selected))
                sample_coalitions.append(named)
    return sample_coalitions


# -------------------------------
# Main Execution
# -------------------------------
if __name__ == "__main__":
    model, rewards, sizes, prob_history = train_rl_policy()

    plt.figure(figsize=(12, 4))
    plt.subplot(1, 3, 1)
    plt.plot(rewards)
    plt.title("Reward Over Time")
    plt.subplot(1, 3, 2)
    plt.plot(sizes)
    plt.title("Coalition Size")
    plt.subplot(1, 3, 3)
    plt.bar(np.arange(N), prob_history.mean(axis=0))
    plt.title("Avg Inclusion Probabilities")
    plt.tight_layout()
    plt.savefig("../rl_realdata_training_summary.png", dpi=300)
    plt.show()
    plt.close()
    print("Saved: rl_realdata_training_summary.png")

    coalitions = sample_learned_coalitions(model)
    pd.DataFrame({"Coalition": coalitions}).drop_duplicates().to_csv(
        "outputs/rl_learned_coalitions_realdata_with_sim_vulnerability.csv", index=False)
    print("Exported: outputs/rl_learned_coalitions_realdata_with_sim_vulnerability.csv")
